#####################################
# Don't touch this file is generated
# expecilly for: ${DC_HOSTNAME}
###################################
#
# Consider to Backup  ${DC_BASE_DATA_DIR}
#
version: "3"
networks:
  devstacknetwork:
    driver: bridge

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins-lts
    ports:
      - 8087:8080
      - 50000:50000
    networks:
      - devstacknetwork
    volumes:
      - ${DC_BASE_DATA_DIR}/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
#-------------------------------------------------------------------------------
  portainer:
    image: portainer/portainer:linux-amd64-1.21.0
    container_name: portainer
    command: --no-auth
    ports:
      - 9001:9000
    networks:
      - devstacknetwork
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ${DC_BASE_DATA_DIR}/portainer_data:/data
#-------------------------------------------------------------------------------
  nexus:
    image: 162.248.163.127:8085/nexus3-20210913
    container_name: sonatype-nexus3
    ports:
      - 8081:8081
      - 8085:8085
    networks:
      - devstacknetwork
    environment:
      - NEXUS_CONTEXT=nexus
      - INSTALL4J_ADD_VM_PARAMS=-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=/nexus-data
    volumes:
      - ${DC_BASE_DATA_DIR}/nexus_data:/nexus-data sonatype/nexus3
#-------------------------------------------------------------------------------
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgreql/data/db-files/
    networks:
      - devstacknetwork
    volumes:
      - /test/postgres-data/postgresql:/var/lib/postgresql
      - /test/postgres-data/postgresql-data:/var/lib/postgresql/data
#-------------------------------------------------------------------------------
  sonarqube:
    image: sonarqube:7.1
    container_name: sonarcube
    ports:
        - 9010:9000
    networks:
       - devstacknetwork
    depends_on:
       - postgres
    environment:
      - sonar.jdbc.url=jdbc:postgresql://postgres/postgres 
      - sonar.jdbc.username=postgres
      - sonar.jdbc.password=admin
    volumes:
      - /test/sonar/sonarqube-conf:/opt/sonarqube/conf
      - /test/sonar/sonarqube-data:/opt/sonarqube/data
      - /test/sonar/sonarqube-extensions:/opt/sonarqube/extensions
      - /test/sonar/sonarqube-bundled-plugins:/opt/sonarqube/lib/bundled-plugins
# ------------------------------------------------------------------------------
  ngnix:
     image: nginx
     container_name: nginx
     ports:
       - 80:80
       - 5434:5432
     networks:
       - devstacknetwork
     depends_on:
       - nexus
       - postgres
       - portainer
       - sonarqube
# ------------------------------------------------------------------------------
#  tomcat:
#    image: tomcat:9.0
#    container_name: pcv-tomcat
#    extra_hosts:
#      - ${DC_HOSTNAME}:${DC_HOSTIP}
#    ports:
#      - "8888:8080"	
#    networks:
#      - devstacknetwork
#    environment:
#      - CATALINA_BASE=/usr/local/tomcat
#      - CATALINA_HOME=/usr/local/tomcat
#      - CATALINA_TMPDIR=/usr/local/tomcat/temp
#      - JRE_HOME=/usr
#      - CLASSPATH=/usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar


      
    
      